ovsx:
  webui:
    url: http://localhost:8080
  ldap:
    url: ${LDAP_URL:ldap://localhost:389}
    base: ${LDAP_BASE:dc=example,dc=com}
    userDn: ${LDAP_USER_DN:}
    password: ${LDAP_PASSWORD:}
    userSearchBase: ${LDAP_USER_SEARCH_BASE:ou=users}
    userSearchFilter: ${LDAP_USER_SEARCH_FILTER:(uid={0})}